### ISSUE TITLE
versioning for reproducibilty

### ISSUE THREAD

**Issue by drcandacemakedamoore** [hannah-horng/opnested-combat#1]
Hi! I'm working on a project where we need to have scientific reproducibility of such an algorithm. As presumably the main will change, it would be great to have versions of this library. Also an environment file, so we know which versions of libraries like pandas are compatible. I could to to do these things on a fork , but if you would like I can add it back here as well.

**Comment by hannah-horng** [comment]
Hi! As requested I've added a requirements.txt file with package versions that I use to run OPNested ComBat. I've also added an archive folder that will contain older versions of the code and a log for all major version updates (version_log.txt). Thanks for using OPNested ComBat and let me know if there's anything else I can help with!
